### PR TITLE
joi v16

### PR DESCRIPTION
**Pull request by hueniverse**
Make sure to note in the readme which version of joi should be used with this module. Optionally, you can check the version of `joi` being passed and assert accordingly. Potentially, you can release one version that supports both joi 16 and 15... I wouldn't do it but just wanted to mention.

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
Looks like CI is failing due to the lock file not being in sync with package.json. I also left you a direct message on the hapi slack regarding this pr and joi in general.

**Comment by hueniverse** [comment]
I don't do lock files. Feel free to update.

**Comment by hueniverse** [comment]
This is ready.

**Comment by AdriVanHoudt** [comment]
Thanks for this. There is a weird `.vs/slnx.sqlite` file in the diff though?
I will merge this when we will work on our Joi 16 migration.

**Comment by joshelson** [comment]
Any chance of getting a merge here? Would be helpful to some of us.

**Comment by AdriVanHoudt** [comment]
@hueniverse Thank you so much for this. I know how limited your time is!
This helped a lot with updating (even though the api changed in between ^^)

**Pull request closed without merging**
