### PR TITLE
feat: add strict validation to phone number as an option

### LINKED ISSUE #57: Bug: Doesn't Use The Phone Utility's isValidNumber() Method
The Google Library has a method for checking to see if the phone number is valid:

```
const phoneUtil = require('google-libphonenumber').PhoneNumberUtil.getInstance();

// Parse number with country code and keep raw input.
const number = phoneUtil.parseAndKeepRawInput('202-456-1414', 'US');

// Result from isValidNumber().
console.log(phoneUtil.isValidNumber(number));
// => true
```

And according to the documentation: `isValidNumber(number) - tests whether a phone number matches a valid pattern.`  (https://github.com/ruimarinho/google-libphonenumber)

The issue is that I don't think the joi-phone-number uses that method to check to see if the phone is valid or not.

I enter in `7777777777` and the joi-phone-number code doesn't flag that as an error. But I type that number into the google utils demo app and it reports that the `isValidNumber(...)` method returns false for the `7777777777` number. See here: http://libphonenumber.appspot.com/phonenumberparser?number=7777777777&country=US

The same thing is true for '1234567890': the joi-phone-number doesn't flag that as an error but the `isValidNumber(...)` method returns false.

So I think there is a bug here.

Here is my joi schema statement:

```
...

// I want the phone number to be a valid phone number according to the Google Phone library
// I want the phone number to still be in the ########## format
// I want the phone number to be allowed to be null and when it is null then default to a specific phone number
// I don't want to convert to the 'e164' format so I use the .raw() to keep the original 10 digit value
// And when the phone number isn't specified at all or is null then I want it to default to a specific phone number.

phone: joi.string().empty(null).regex(/^\d{10}$/).phoneNumber({ defaultCountry: 'US', format: 'e164' }).raw().default('5152987228'),

...
```

### PR DESCRIPTION
**Pull request by optii**
Resolves #57.

Adds an option `strict` to define if `isValidNumber` should be checked against the formatted number. 

This is a quick first draft, will need to update the `README.md` & add some more tests. 

Let me know

### CODE REVIEW

**Comment by iraycd** [comment]
Merge this please.

**Comment by AdriVanHoudt** [comment]
I like the solution! Thanks for this!
If you can add some more test and update the readme I will gladly merge this ✨

**Comment by CatGuardian** [comment]
How is this coming along @optii? Are we getting close to having this wrapped up?

**Comment by optii** [comment]
Just pushed some updates, I've updated the test, to use the examples given in issue #57, a bit stuck as to what other test i could possibly add tbh. Added the example to the readme, don't know if how I've done it is what you where expecting ? happy to make changes if you've got any suggestions

**Comment by AdriVanHoudt** [comment]
Thanks for this!
Released under 3.1.0 :shipit:

**Pull request merged**
